#!/bin/bash

db_user=drupalabx
db_name=drupalabx
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting drupalabx domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/drupalabx
sudo rm -f /etc/nginx/conf.d/$domain.d/drupalabx.conf
